### ISSUE TITLE
could not find clickable node

### ISSUE THREAD

**Issue by thatsgraphic** [eflorit/bloodpoints-spender#2]
not sure why. But my mouse goes to the top left to the take the clean screen shot, and then i get the error of not finding any clickable nodes. Doesnt work at all for me

**Comment by eflorit** [comment]
Hello.

Please make sure you answer yes to all the following:

- Did you make sure you unzipped the entire folder before running the exe file? (don't run it straight from the archive)
- Did you make sure your game runs in `1920x1080`?
- Are your graphics on `Low`?
- Did you make sure you turned off any filter your graphics card may add (Nvidia, etc)?
- Do you make sure you stay on the bloodweb screen the whole time?

If so, feel free to share your `tmp-screenshot.png` so I can take try to identify what's wrong in it

**Comment by gmakki** [comment]
Im using 1920x1080 resolution. But when i look into the screenshot it looks like is cropped somehow.
Graphics in low
Full screeen mode
100% rescaling (off)

When i try reducing the resolution. It then finds the nodes but when it goes to click on it. The click coordinates must be mistaken due to the lower resolution

So my hypothesis for the problem is:
The tracking is not working on the 1920x1080 resolution due it is cropping somehow.
When i can fix this by reducing resolution, the click coordinates is wrong (because it is set to the 1920x1080 res)

**Comment by eflorit** [comment]
Can you share the screenshot? Feel free to paint over your username or something if you want to keep it private. If you do though, make sure you save the image in the highest quality possible and without resizing.

Do you have 2 monitors maybe? Or 2 displays of some kind?

**Comment by gmakki** [comment]
Oh thank you for replying sooo quickly. 
So i manage to make it work. Windows has this config to increase fonts and other things in 125% when it uses this reolution. I changed it to 100%
i also have a second monitor and i turned off the laptop one and left only the monitor on in the the 1920x1080resolution

now it worked just fine. 

Thank you so much for sharing this, this will save me lots of time ❤️❤️
Best regards!
